"""
TrialMatch AI Report Generator Service

Generates professional PDF reports of screening results.

Uses reportlab to create:
1. Header with trial info and patient ID
2. Overall eligibility summary
3. Detailed criterion-by-criterion assessment table
4. Missing data section with clinical follow-ups
5. Legal disclaimer and metadata
"""

import logging
import io
from datetime import datetime
from typing import Dict, Any, List, Optional

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white, green, red, orange, lightgrey
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer,
    PageBreak, Image, KeepTogether
)
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from ..models.screening import (
    ScreeningResult, CriterionAssessment, OverallStatus,
    PatientSummary, AssessmentStatus, ConfidenceLevel
)


logger = logging.getLogger(__name__)


# ============================================================================
# LEGAL DISCLAIMER
# ============================================================================

DISCLAIMER_TEXT = """
DISCLAIMER AND IMPORTANT NOTICE

This TrialMatch AI screening report is generated by an automated system to assist healthcare
professionals in identifying potential clinical trial eligibility. This report:

1. IS NOT A MEDICAL DIAGNOSIS OR CLINICAL DECISION
   - This tool provides algorithmic matching against stated criteria only
   - A qualified healthcare professional must review all results
   - Clinical judgment and manual verification are required

2. REQUIRES HUMAN REVIEW
   - All findings marked "INSUFFICIENT_DATA" must be clarified through direct patient assessment
   - Criteria marked "NEEDS_REVIEW" require clinician interpretation
   - Do not make enrollment decisions based solely on this report

3. MAY CONTAIN ERRORS
   - Automated extraction from protocols may misinterpret complex criteria
   - Patient data entered may be incomplete or inaccurate
   - OCR extraction from scanned PDFs may contain errors

4. IS NOT A SUBSTITUTE FOR PROTOCOL REVIEW
   - The original trial protocol is the authoritative source
   - All eligibility determinations must be confirmed against the actual protocol
   - Contact the trial sponsor for ambiguous criteria

5. DE-IDENTIFICATION REQUIREMENT
   - This tool is designed for de-identified patient data only
   - Do not enter patient names, dates of birth, medical record numbers
   - Ensure all patient information is properly de-identified before use

6. CONFIDENTIALITY
   - Treat this report as confidential patient health information
   - Follow HIPAA and applicable privacy regulations
   - Secure storage and access controls are your responsibility

By using this report, you acknowledge that a qualified healthcare professional will
review and validate all findings before making any trial enrollment decisions.

Report Generated: {generated_at}
TrialMatch AI Version: 1.0
"""


# ============================================================================
# REPORT GENERATOR
# ============================================================================

class ReportGenerator:
    """
    Generates professional PDF screening reports.

    Creates a multi-section document with:
    - Professional formatting and branding
    - Clear visual status indicators (green/red/yellow)
    - Detailed assessment information
    - Actionable follow-up guidance
    - Legal disclaimers and metadata
    """

    def __init__(self):
        """Initialize report generator"""
        self.page_width, self.page_height = letter
        self.margin = 0.5 * inch

    def generate_report(
        self,
        screening_result: ScreeningResult,
        patient_summary: PatientSummary,
        trial_info: Dict[str, str]
    ) -> bytes:
        """
        Generate PDF report from screening results.

        Args:
            screening_result: Complete screening result
            patient_summary: Patient data used in screening
            trial_info: Trial metadata (name, phase, sponsor, etc.)

        Returns:
            PDF file as bytes

        Raises:
            ValueError: If report generation fails
        """

        try:
            # [IMPLEMENTATION]: Create PDF document in memory
            pdf_buffer = io.BytesIO()

            doc = SimpleDocTemplate(
                pdf_buffer,
                pagesize=letter,
                rightMargin=self.margin,
                leftMargin=self.margin,
                topMargin=self.margin,
                bottomMargin=self.margin,
                title="TrialMatch AI Screening Report"
            )

            # [IMPLEMENTATION]: Build report sections
            story = []

            # Header section
            story.extend(self._create_header_section(trial_info))
            story.append(Spacer(1, 0.3 * inch))

            # Summary section
            story.extend(self._create_summary_section(screening_result))
            story.append(Spacer(1, 0.2 * inch))

            # Criteria assessment table
            criteria_table = self._create_criteria_table(screening_result.assessments)
            story.append(criteria_table)
            story.append(Spacer(1, 0.2 * inch))

            # Detailed criterion assessments
            for assessment in screening_result.assessments:
                detail = self._create_criterion_detail(assessment)
                story.extend(detail)

            # Missing data section
            if screening_result.missing_data_summary:
                story.append(Spacer(1, 0.3 * inch))
                story.extend(self._create_missing_data_section(screening_result))

            # Follow-up questions
            if screening_result.follow_up_questions:
                story.append(Spacer(1, 0.3 * inch))
                story.extend(self._create_followup_section(screening_result))

            # Disclaimer
            story.append(PageBreak())
            story.extend(self._create_disclaimer_section(screening_result))

            # [IMPLEMENTATION]: Build PDF and return bytes
            doc.build(story)
            pdf_bytes = pdf_buffer.getvalue()

            logger.info(f"Generated PDF report: {len(pdf_bytes)} bytes")
            return pdf_bytes

        except Exception as e:
            logger.error(f"Report generation failed: {e}")
            raise ValueError(f"Failed to generate PDF report: {str(e)}")

    def _create_header_section(self, trial_info: Dict[str, str]) -> List:
        """
        Create report header with trial and document information.

        Args:
            trial_info: Trial metadata

        Returns:
            List of reportlab Story elements
        """

        styles = getSampleStyleSheet()
        story = []

        # [IMPLEMENTATION]: Trial name as main title
        trial_name = trial_info.get('trial_name', 'Unknown Trial')
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=HexColor("#1F2937"),
            spaceAfter=12
        )
        story.append(Paragraph(f"Trial Eligibility Screening Report", title_style))

        # [IMPLEMENTATION]: Trial metadata
        trial_name_para = Paragraph(
            f"<b>Trial:</b> {trial_name}",
            styles['Normal']
        )
        story.append(trial_name_para)

        if trial_info.get('trial_phase'):
            story.append(
                Paragraph(
                    f"<b>Phase:</b> {trial_info['trial_phase']}",
                    styles['Normal']
                )
            )

        if trial_info.get('trial_sponsor'):
            story.append(
                Paragraph(
                    f"<b>Sponsor:</b> {trial_info['trial_sponsor']}",
                    styles['Normal']
                )
            )

        # [IMPLEMENTATION]: Report metadata
        story.append(Spacer(1, 0.15 * inch))
        story.append(
            Paragraph(
                f"<b>Report Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
                styles['Normal']
            )
        )

        return story

    def _create_summary_section(self, screening_result: ScreeningResult) -> List:
        """
        Create overall eligibility summary with visual status indicator.

        Args:
            screening_result: Screening results

        Returns:
            List of reportlab Story elements
        """

        styles = getSampleStyleSheet()
        story = []

        # [IMPLEMENTATION]: Status badge with color coding
        overall_status = screening_result.overall_status

        if overall_status == OverallStatus.LIKELY_ELIGIBLE:
            status_color = HexColor("#10B981")  # Green
            status_text = "LIKELY ELIGIBLE"
            status_detail = "Patient appears to meet eligibility criteria for this trial."
        elif overall_status == OverallStatus.LIKELY_INELIGIBLE:
            status_color = HexColor("#EF4444")  # Red
            status_text = "LIKELY INELIGIBLE"
            status_detail = "Patient does not meet one or more eligibility criteria."
        else:  # NEEDS_REVIEW
            status_color = HexColor("#F59E0B")  # Orange
            status_text = "NEEDS REVIEW"
            status_detail = "Insufficient data or mixed results. Manual review required."

        # [IMPLEMENTATION]: Build status paragraph
        status_style = ParagraphStyle(
            'Status',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=status_color,
            spaceAfter=6
        )
        story.append(Paragraph(f"Overall Status: {status_text}", status_style))
        story.append(Paragraph(status_detail, styles['Normal']))

        # [IMPLEMENTATION]: Add summary statistics
        story.append(Spacer(1, 0.1 * inch))

        meets_count = sum(
            1 for a in screening_result.assessments
            if a.status == AssessmentStatus.MEETS
        )
        does_not_meet = sum(
            1 for a in screening_result.assessments
            if a.status == AssessmentStatus.DOES_NOT_MEET
        )
        insufficient = sum(
            1 for a in screening_result.assessments
            if a.status == AssessmentStatus.INSUFFICIENT_DATA
        )

        summary_text = (
            f"<b>Criteria Summary:</b> {meets_count} meets, "
            f"{does_not_meet} does not meet, {insufficient} insufficient data"
        )
        story.append(Paragraph(summary_text, styles['Normal']))

        return story

    def _create_criteria_table(self, assessments: List[CriterionAssessment]) -> Table:
        """
        Create table of all criterion assessments.

        Table columns: Criterion ID, Type, Status, Confidence

        Args:
            assessments: List of criterion assessments

        Returns:
            reportlab Table element
        """

        # [IMPLEMENTATION]: Build table data
        table_data = [
            ['Criterion', 'Status', 'Confidence', 'Evidence']
        ]

        for assessment in assessments:
            # [IMPLEMENTATION]: Map status to display text
            if assessment.status == AssessmentStatus.MEETS:
                status_text = "✓ Meets"
            elif assessment.status == AssessmentStatus.DOES_NOT_MEET:
                status_text = "✗ Does Not Meet"
            else:
                status_text = "? Insufficient Data"

            # [IMPLEMENTATION]: Get confidence display
            confidence_text = assessment.confidence.value.title()

            # [IMPLEMENTATION]: Evidence summary (first evidence item)
            evidence_text = (
                assessment.evidence_cited[0][:50] + "..."
                if assessment.evidence_cited
                else "No evidence cited"
            )

            table_data.append([
                assessment.criterion_id,
                status_text,
                confidence_text,
                evidence_text
            ])

        # [IMPLEMENTATION]: Create table with styling
        table = Table(table_data, colWidths=[1.0 * inch, 1.5 * inch, 1.2 * inch, 2.3 * inch])

        # [IMPLEMENTATION]: Apply table styling
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor("#374151")),
            ('TEXTCOLOR', (0, 0), (-1, 0), white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, HexColor("#F9FAFB")])
        ]))

        return table

    def _create_criterion_detail(self, assessment: CriterionAssessment) -> List:
        """
        Create detailed section for a single criterion assessment.

        Args:
            assessment: Criterion assessment

        Returns:
            List of reportlab Story elements
        """

        styles = getSampleStyleSheet()
        story = []

        # [IMPLEMENTATION]: Criterion ID and status header
        detail_style = ParagraphStyle(
            'DetailHeader',
            parent=styles['Heading3'],
            fontSize=11,
            textColor=black,
            spaceAfter=6
        )

        story.append(Spacer(1, 0.1 * inch))
        story.append(
            Paragraph(
                f"<b>Criterion {assessment.criterion_id}</b>: {assessment.status.value.replace('_', ' ').title()}",
                detail_style
            )
        )

        # [IMPLEMENTATION]: Reasoning
        story.append(
            Paragraph(f"<b>Rationale:</b> {assessment.reasoning}", styles['Normal'])
        )

        # [IMPLEMENTATION]: Evidence cited
        if assessment.evidence_cited:
            evidence_text = "<b>Evidence:</b> " + "; ".join(assessment.evidence_cited)
            story.append(Paragraph(evidence_text, styles['Normal']))

        # [IMPLEMENTATION]: Missing data if applicable
        if assessment.missing_data:
            missing_text = "<b>Missing Data:</b> " + "; ".join(assessment.missing_data)
            story.append(Paragraph(missing_text, styles['Normal']))

        return story

    def _create_missing_data_section(self, screening_result: ScreeningResult) -> List:
        """
        Create section listing missing data across all criteria.

        Args:
            screening_result: Screening results

        Returns:
            List of reportlab Story elements
        """

        styles = getSampleStyleSheet()
        story = []

        # [IMPLEMENTATION]: Header
        story.append(
            Paragraph("<b>Missing Data</b>", styles['Heading2'])
        )
        story.append(
            Paragraph(
                "The following clinical information was not available and would help "
                "clarify eligibility:",
                styles['Normal']
            )
        )

        # [IMPLEMENTATION]: Build bullet list
        story.append(Spacer(1, 0.1 * inch))
        for idx, item in enumerate(screening_result.missing_data_summary, 1):
            story.append(Paragraph(f"• {item}", styles['Normal']))

        return story

    def _create_followup_section(self, screening_result: ScreeningResult) -> List:
        """
        Create section with follow-up questions for clinicians.

        Args:
            screening_result: Screening results

        Returns:
            List of reportlab Story elements
        """

        styles = getSampleStyleSheet()
        story = []

        # [IMPLEMENTATION]: Header
        story.append(
            Paragraph("<b>Recommended Follow-Up Questions</b>", styles['Heading2'])
        )
        story.append(
            Paragraph(
                "Consider asking the patient or reviewing records for the following:",
                styles['Normal']
            )
        )

        # [IMPLEMENTATION]: Build numbered list
        story.append(Spacer(1, 0.1 * inch))
        for idx, question in enumerate(screening_result.follow_up_questions, 1):
            story.append(Paragraph(f"{idx}. {question}", styles['Normal']))

        return story

    def _create_disclaimer_section(self, screening_result: ScreeningResult) -> List:
        """
        Create final disclaimer and metadata section.

        Args:
            screening_result: Screening results

        Returns:
            List of reportlab Story elements
        """

        styles = getSampleStyleSheet()
        story = []

        # [IMPLEMENTATION]: Disclaimer heading
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Heading2'],
            fontSize=12,
            textColor=HexColor("#EF4444"),
            spaceAfter=12
        )
        story.append(Paragraph("<b>DISCLAIMER AND IMPORTANT NOTICE</b>", disclaimer_style))

        # [IMPLEMENTATION]: Disclaimer body
        disclaimer_body = DISCLAIMER_TEXT.format(
            generated_at=datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
        )
        story.append(Paragraph(disclaimer_body, styles['Normal']))

        # [IMPLEMENTATION]: Metadata footer
        story.append(Spacer(1, 0.2 * inch))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=HexColor("#6B7280")
        )

        metadata = (
            f"Screening ID: {screening_result.screening_id} | "
            f"Protocol: {screening_result.protocol_id} | "
            f"Patient: {screening_result.patient_id} | "
            f"Time: {screening_result.assessed_at.isoformat()}"
        )
        story.append(Paragraph(metadata, footer_style))

        return story
